# Generated by Django 5.0 on 2025-01-19 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergame', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='failure_message',
            field=models.TextField(default='Incorrect. Try again.'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='interaction_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='challenge',
            name='learning_points',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='challenge',
            name='success_message',
            field=models.TextField(default='Correct! Well done.'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='environment_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scenario',
            name='learning_objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scenario',
            name='recommended_time',
            field=models.IntegerField(default=60, help_text='Recommended time in minutes'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='scenario_type',
            field=models.CharField(choices=[('PHISHING', 'Phishing Attack'), ('DDOS', 'DDoS Attack'), ('RANSOMWARE', 'Ransomware Attack'), ('PASSWORD', 'Password Security'), ('SQL_INJECTION', 'SQL Injection'), ('XSS', 'Cross-Site Scripting')], default='PASSWORD', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='time_limit',
            field=models.IntegerField(default=3600, help_text='Time limit in seconds'),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('completion_time', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybergame.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
