# Generated by Django 5.0 on 2025-01-22 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cybergame', '0002_challenge_failure_message_challenge_interaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='correct_answer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='question',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cybergame.scenario'),
        ),
        migrations.AlterField(
            model_name='scenario',
            name='time_limit',
            field=models.IntegerField(help_text='Time limit in seconds'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
